#
# Package stage
#
FROM openjdk:11-jre-slim

RUN apt-get update   && apt-get install -y curl

COPY  ./target/HelloWorldSpringWebProject-*.jar /usr/local/lib/app.jar

ENV FRONTEND_BASEURIS_0=willbeoverritten
ENV FRONTEND_BASEURIS_1=willbeoverritten
EXPOSE 2200
ENTRYPOINT ["java","-jar","/usr/local/lib/app.jar"]

